//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaNomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asistencia
    {
        public int id_asistencia { get; set; }
        public int id_empleado { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<System.TimeSpan> hora_entrada { get; set; }
        public Nullable<System.TimeSpan> hora_salida { get; set; }
        public Nullable<bool> es_feriado { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<int> id_feriado { get; set; }
    
        public virtual Empleados Empleados { get; set; }
        public virtual Feriados Feriados { get; set; }
    }
}
