//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaNomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incapacidades
    {
        public int id_incapacidad { get; set; }
        public int id_empleado { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public System.DateTime fecha_fin { get; set; }
        public string numero_boleta { get; set; }
        public Nullable<int> id_tipo_incapacidad { get; set; }
        public string descripcion { get; set; }
        public int id_estado { get; set; }
        public Nullable<int> dias_incapacidad { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
    
        public virtual Empleados Empleados { get; set; }
        public virtual Estados Estados { get; set; }
        public virtual TipoIncapacidades TipoIncapacidades { get; set; }
    }
}
