//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaNomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nomina
    {
        public int id_nomina { get; set; }
        public int id_empleado { get; set; }
        public int id_isr { get; set; }
        public int mes { get; set; }
        public int anio { get; set; }
        public decimal salario_bruto { get; set; }
        public Nullable<decimal> horas_extras { get; set; }
        public Nullable<decimal> salario_dias_feriados { get; set; }
        public Nullable<decimal> ccss { get; set; }
        public Nullable<decimal> ivm { get; set; }
        public Nullable<decimal> isr { get; set; }
        public Nullable<decimal> credito_hijos { get; set; }
        public Nullable<decimal> credito_conyuge { get; set; }
        public Nullable<decimal> otros_descuentos { get; set; }
        public Nullable<decimal> base_imponible { get; set; }
        public decimal salario_neto { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_actualizacion { get; set; }
    
        public virtual Empleados Empleados { get; set; }
        public virtual ISR ISR1 { get; set; }
    }
}
