//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaNomina
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permisos
    {
        public int id_permiso { get; set; }
        public int id_empleado { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<decimal> horas { get; set; }
        public int id_tipo_permiso { get; set; }
        public string motivo { get; set; }
        public int id_estado { get; set; }
        public Nullable<int> aprobado_por { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_actualizacion { get; set; }
    
        public virtual Empleados Empleados { get; set; }
        public virtual Estados Estados { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual TiposPermiso TiposPermiso { get; set; }
    }
}
